import React from 'react';
import { Check, LockKeyhole, ShieldAlert } from 'lucide-react';

import { useDashboard } from '../hooks/useDashboardData';
import AIInsightPanel from '../components/AIInsightPanel';
import { Card, CardContent } from '../components/ui/card';
import { ScreenHeading, SectionHeading } from '../components/ui/section-heading';

/** What the daemon strips before anything leaves the machine. */
const REDACTED = [
  'CPU, memory, disk, network and process aggregates are included.',
  'The hostname is retained so a fleet-wide answer can be correlated.',
  'IP and e-mail addresses and home-directory usernames are removed from logs and process names.',
];

const Insights: React.FC = () => {
  const { ai } = useDashboard();

  return (
    <>
      <ScreenHeading
        eyebrow="Accountable assistance"
        title="AI insights"
        description="A diagnosis is only useful when its evidence, its boundaries and its suggested actions are all visible."
      />

      <div className="grid grid-cols-1 items-start gap-4 lg:grid-cols-[minmax(0,1.3fr)_minmax(280px,0.7fr)]">
        <AIInsightPanel
          analysis={ai.result}
          error={ai.error}
          loading={ai.loading}
          onRefresh={ai.run}
        />

        <Card>
          <CardContent className="p-5">
            <SectionHeading eyebrow="Data boundary" title="What left the host" />

            {/* Stated as a list of facts rather than a paragraph of policy.
                Anyone deciding whether to enable this feature is auditing it,
                and an audit is a checklist. */}
            <ul className="text-muted-foreground mt-5 space-y-4 text-2xs leading-relaxed">
              {REDACTED.map((item) => (
                <li key={item} className="flex gap-3">
                  <Check className="text-ok mt-0.5 size-4 shrink-0" aria-hidden="true" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>

            <div className="border-warn/30 bg-warn-soft mt-6 flex gap-2.5 rounded-lg border p-3">
              <ShieldAlert className="text-warn mt-0.5 size-4 shrink-0" aria-hidden="true" />
              <p className="text-warn text-xs leading-relaxed">
                Recommended commands are generated by a language model and are not validated by the
                daemon. Read them before running anything, and never paste one into a root shell
                unexamined.
              </p>
            </div>

            <div className="border-line bg-panel-strong text-mute mt-4 rounded-md border p-3 text-2xs leading-relaxed">
              <LockKeyhole className="text-brand mb-2 size-4" aria-hidden="true" />
              Analysis runs against a single current sample plus recent logs. It is triggered
              automatically when CPU or memory crosses a threshold, and manually from this page.
              Gemini access is configured by the administrator and is off until a key is set.
            </div>
          </CardContent>
        </Card>
      </div>
    </>
  );
};

export default Insights;
